import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "../utils/providers";
import Header from "@/components/commons/Header";
import { ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

// SEO 기본 데이터
// 이것이 검색 조건
// NEXT는 SEO의 사이트 맵을 자동 생성(SSR 덕분에) - 리액트는 직접 설정
// SEARCH CONSOLE -
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, modal }: { children: React.ReactNode; modal: ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Providers>{children}</Providers>
        {modal}
        <div id="modal-root" className="relative z-50" />
      </body>
    </html>
  );
}
